import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "../globals.css";
import { Providers } from "../(landing_page)/providers";
import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";
import LeftSidebar from "@/components/LeftSidebar";
import Image from "next/image";
import { BackgroundBeams } from "@/components/ui/backgroundBeams";
import { QueryProvider } from "@/components/QueryPovider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "main",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body className={inter.className}>
          <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }}>
            <Navbar />

            <main className="flex flex-row">
              <LeftSidebar />
              <section className="main-container">
                <div className="w-full max-w-4xl">
                  <QueryProvider>
                    {children}
                    <Toaster richColors position="top-center" />
                  </QueryProvider>
                </div>
              </section>
              <div className="-z-10">
                <BackgroundBeams />
              </div>
            </main>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
