import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Navbar } from "@/components/Navbar";
import Image from "next/image";
import Topbar from "@/components/Topbar";
import { BackgroundBeams } from "@/components/ui/backgroundBeams";
import { QueryProvider } from "@/components/QueryPovider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body className={inter.className}>
          <Topbar />
          <main className="flex flex-row px-20 py-12 max-sm:px-4">
            <section className="main-container">
              <div className="w-full ">
                <QueryProvider>
                  {children}

                  <Toaster duration={2000} position="top-center" richColors />
                </QueryProvider>
              </div>
            </section>
            <div className="-z-10">
              <BackgroundBeams />
            </div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
