import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { Navbar } from '@/components/Navbar'
import Image from 'next/image'
import Topbar from '@/components/Topbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en" className='dark' >
        <body className={inter.className}>
              <Topbar />
        <main className='flex flex-row px-20 py-12'>
        
          <section className='main-container'>
             <div className='w-full '>
               {children}
             </div>
          </section>
       
        <Image src="/assets/images/user.png"
         alt=" constructor" 
         width={300}
          height={300}
          className="object-cover rounded-lg h-60 mt-40"
        />
    
         </main>

        </body>
      </html>
    </ClerkProvider>
  )
}
